version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src/htdocs:/var/www/html/public
        ports:
            - 28080:80
        restart: always
        depends_on:
            - php
            - db
    php:
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./src/htdocs:/var/www/html/public
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
    db:
        image: postgres:10.1
        restart: always
#        command: postgres -c config_file=/etc/postgresql.conf
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 54321:5432
        volumes:
            - ./src/dump:/var/dump
            - ./src/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
            - ./database:/var/lib/postgresql/data
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
